export interface DiagnosisEntry {
  id: string;
  name: string;
  icd10: string;
  dsm5: string | null;
  category: string;
  description: string;
  isCustom?: boolean;
}

export interface DiagnosisInstance extends DiagnosisEntry {
  isPrimary?: boolean;
}

export const DIAGNOSIS_LIBRARY: DiagnosisEntry[] = [
  // ─── Autism Spectrum & Developmental ───
  { id: "asd_1", name: "Autism Spectrum Disorder — Level 1 (Requiring support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "A neurodevelopmental condition characterised by persistent difficulties with social communication and interaction, and restricted, repetitive patterns of behaviour, interests, or activities. Level 1 indicates the individual requires support to function in one or more contexts." },
  { id: "asd_2", name: "Autism Spectrum Disorder — Level 2 (Requiring substantial support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder with marked deficits in verbal and non-verbal social communication, social impairments apparent even with supports in place, and inflexible behaviour that interferes with functioning across contexts." },
  { id: "asd_3", name: "Autism Spectrum Disorder — Level 3 (Requiring very substantial support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder with severe deficits in verbal and non-verbal social communication causing severe impairments in functioning, very limited initiation of social interactions, and inflexibility of behaviour that markedly interferes with functioning in all spheres." },
  { id: "asd_unspec", name: "Autism Spectrum Disorder — Unspecified Level", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder where the level of support required has not yet been formally classified." },
  { id: "adhd_combined", name: "Attention-Deficit/Hyperactivity Disorder — Combined Presentation", icd10: "F90.2", dsm5: "314.01", category: "Neurodevelopmental", description: "A neurodevelopmental disorder characterised by a persistent pattern of inattention and hyperactivity-impulsivity that interferes with functioning or development." },
  { id: "adhd_inattentive", name: "Attention-Deficit/Hyperactivity Disorder — Predominantly Inattentive", icd10: "F90.0", dsm5: "314.00", category: "Neurodevelopmental", description: "ADHD with predominant symptoms of inattention including difficulty sustaining attention, poor organisation, distractibility, and forgetfulness in daily activities." },
  { id: "adhd_hyperactive", name: "Attention-Deficit/Hyperactivity Disorder — Predominantly Hyperactive-Impulsive", icd10: "F90.1", dsm5: "314.01", category: "Neurodevelopmental", description: "ADHD with predominant symptoms of hyperactivity and impulsivity including fidgeting, difficulty remaining seated, excessive talking, and difficulty waiting." },
  // ─── Intellectual Disability ───
  { id: "id_mild", name: "Intellectual Disability — Mild", icd10: "F70", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 50–69, characterised by slower learning, difficulties with abstract thinking, and reduced adaptive functioning in conceptual, social, and practical domains." },
  { id: "id_moderate", name: "Intellectual Disability — Moderate", icd10: "F71", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 35–49, characterised by significant delays in development, limited communication skills, and the need for ongoing support with daily living skills." },
  { id: "id_severe", name: "Intellectual Disability — Severe", icd10: "F72", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 20–34, characterised by very limited communication, dependence on others for all self-care, and the need for continuous supervision and support." },
  { id: "id_profound", name: "Intellectual Disability — Profound", icd10: "F73", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability with an IQ below 20, characterised by very limited communication and motor function, total dependence on others for all aspects of daily care, and the need for 24-hour support." },
  { id: "id_unspec", name: "Intellectual Disability — Unspecified", icd10: "F79", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability where the severity level has not been formally determined but significant deficits in intellectual and adaptive functioning are present." },
  { id: "gdd", name: "Global Developmental Delay", icd10: "F88", dsm5: "315.8", category: "Neurodevelopmental", description: "A diagnosis for children under 5 years who do not meet expected developmental milestones in several areas of intellectual functioning and where clinical severity cannot yet be reliably assessed." },
  // ─── Psychosocial / Mood Disorders ───
  { id: "mdd_single", name: "Major Depressive Disorder — Single Episode", icd10: "F32", dsm5: "296.2x", category: "Psychosocial", description: "A mood disorder characterised by a single episode of persistent low mood, loss of interest or pleasure, and associated symptoms including fatigue, sleep disturbance, appetite changes, and difficulty concentrating." },
  { id: "mdd_recurrent", name: "Major Depressive Disorder — Recurrent", icd10: "F33", dsm5: "296.3x", category: "Psychosocial", description: "A mood disorder with recurrent episodes of persistent depressed mood, loss of interest, and associated symptoms, with a pattern of relapse and recovery." },
  { id: "bpad_1", name: "Bipolar I Disorder", icd10: "F31.1", dsm5: "296.4x", category: "Psychosocial", description: "A mood disorder characterised by at least one manic episode, which may be preceded or followed by hypomanic or major depressive episodes. Manic episodes involve persistently elevated, expansive, or irritable mood with increased energy." },
  { id: "bpad_2", name: "Bipolar II Disorder", icd10: "F31.81", dsm5: "296.89", category: "Psychosocial", description: "A mood disorder characterised by at least one hypomanic episode and at least one major depressive episode, without a full manic episode." },
  { id: "sad", name: "Schizoaffective Disorder", icd10: "F25", dsm5: "295.70", category: "Psychosocial", description: "A disorder characterised by a combination of schizophrenia symptoms (hallucinations, delusions) and mood disorder symptoms (depression or mania)." },
  { id: "schizophrenia", name: "Schizophrenia", icd10: "F20", dsm5: "295.90", category: "Psychosocial", description: "A chronic psychotic disorder characterised by disturbances in thought, perception, and behaviour, including hallucinations, delusions, disorganised speech, and negative symptoms such as reduced emotional expression." },
  { id: "schizo_paranoid", name: "Schizophrenia — Paranoid Type", icd10: "F20.0", dsm5: "295.90", category: "Psychosocial", description: "Schizophrenia predominantly characterised by paranoid delusions and auditory hallucinations, with relatively preserved cognitive functioning and affect." },
  // ─── Anxiety & Trauma ───
  { id: "gad", name: "Generalised Anxiety Disorder", icd10: "F41.1", dsm5: "300.02", category: "Anxiety", description: "An anxiety disorder characterised by excessive, persistent worry about a range of everyday concerns that is difficult to control and causes significant distress or impairment." },
  { id: "social_anx", name: "Social Anxiety Disorder (Social Phobia)", icd10: "F40.10", dsm5: "300.23", category: "Anxiety", description: "An anxiety disorder characterised by marked fear or anxiety about social situations in which the individual may be exposed to scrutiny by others." },
  { id: "panic", name: "Panic Disorder", icd10: "F41.0", dsm5: "300.01", category: "Anxiety", description: "An anxiety disorder characterised by recurrent, unexpected panic attacks with intense physical symptoms including heart palpitations, shortness of breath, and fear of losing control." },
  { id: "agoraphobia", name: "Agoraphobia", icd10: "F40.00", dsm5: "300.22", category: "Anxiety", description: "An anxiety disorder characterised by marked fear or anxiety about situations where escape might be difficult, such as public transport, open spaces, enclosed spaces, crowds, or being outside the home alone." },
  { id: "ocd", name: "Obsessive-Compulsive Disorder", icd10: "F42", dsm5: "300.3", category: "Anxiety", description: "A disorder characterised by recurrent, intrusive obsessions and/or repetitive compulsive behaviours that are time-consuming and cause significant distress or functional impairment." },
  { id: "ptsd", name: "Post-Traumatic Stress Disorder", icd10: "F43.10", dsm5: "309.81", category: "Trauma", description: "A disorder that develops following exposure to a traumatic event, characterised by intrusive re-experiencing, avoidance of trauma-related stimuli, negative alterations in cognition and mood, and marked alterations in arousal and reactivity." },
  { id: "cptsd", name: "Complex Post-Traumatic Stress Disorder", icd10: "F43.10", dsm5: null, category: "Trauma", description: "A condition arising from prolonged, repeated trauma characterised by PTSD symptoms plus disturbances in self-organisation including affect dysregulation, negative self-concept, and difficulties in relationships." },
  // ─── Personality Disorders ───
  { id: "bpd", name: "Borderline Personality Disorder", icd10: "F60.3", dsm5: "301.83", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of instability in interpersonal relationships, self-image, and affect, with marked impulsivity including self-harm and suicidal behaviour." },
  { id: "eupd", name: "Emotionally Unstable Personality Disorder", icd10: "F60.3", dsm5: null, category: "Personality", description: "ICD-10 equivalent of Borderline Personality Disorder, characterised by emotional instability, impulsive behaviour, and difficulties maintaining stable relationships." },
  // ─── Neurodegenerative / Acquired Brain Injury ───
  { id: "tbi", name: "Traumatic Brain Injury", icd10: "S06.9", dsm5: null, category: "Acquired Brain Injury", description: "Brain injury caused by an external mechanical force, resulting in temporary or permanent impairment of cognitive, physical, and psychosocial functions." },
  { id: "abi_anoxic", name: "Acquired Brain Injury — Anoxic/Hypoxic", icd10: "G93.1", dsm5: null, category: "Acquired Brain Injury", description: "Brain injury resulting from insufficient oxygen supply to the brain, causing damage to cognitive, physical, and behavioural functions." },
  { id: "stroke_left", name: "Cerebrovascular Accident (Stroke) — Left Hemisphere", icd10: "I63.9", dsm5: null, category: "Neurological", description: "A stroke affecting the left hemisphere of the brain, commonly resulting in right-sided weakness or paralysis, speech and language difficulties (aphasia), and cognitive impairments." },
  { id: "stroke_right", name: "Cerebrovascular Accident (Stroke) — Right Hemisphere", icd10: "I63.9", dsm5: null, category: "Neurological", description: "A stroke affecting the right hemisphere of the brain, commonly resulting in left-sided weakness or paralysis, spatial awareness difficulties, and changes to perception and behaviour." },
  { id: "ms", name: "Multiple Sclerosis", icd10: "G35", dsm5: null, category: "Neurological", description: "A chronic, progressive autoimmune disease of the central nervous system causing demyelination, leading to variable symptoms including fatigue, mobility impairment, sensory disturbance, cognitive changes, and visual disturbance." },
  { id: "parkinsons", name: "Parkinson's Disease", icd10: "G20", dsm5: null, category: "Neurological", description: "A progressive neurodegenerative disorder characterised by tremor, rigidity, bradykinesia (slowness of movement), and postural instability, with associated non-motor symptoms including cognitive decline and mood disturbance." },
  { id: "mnd", name: "Motor Neurone Disease (ALS)", icd10: "G12.2", dsm5: null, category: "Neurological", description: "A progressive, fatal neurodegenerative disease affecting motor neurones, leading to progressive muscle weakness, wasting, and eventually loss of voluntary movement, speech, swallowing, and breathing." },
  { id: "huntingtons", name: "Huntington's Disease", icd10: "G10", dsm5: null, category: "Neurological", description: "A hereditary, progressive neurodegenerative disorder characterised by involuntary movements (chorea), cognitive decline, and psychiatric disturbance." },
  { id: "epilepsy", name: "Epilepsy", icd10: "G40", dsm5: null, category: "Neurological", description: "A chronic neurological condition characterised by recurrent, unprovoked seizures due to abnormal electrical activity in the brain." },
  // ─── Muscular Dystrophy & Physical ───
  { id: "dmd", name: "Duchenne Muscular Dystrophy", icd10: "G71.01", dsm5: null, category: "Muscular/Physical", description: "A genetic, progressive muscle-wasting condition affecting primarily males, characterised by progressive proximal muscle weakness beginning in early childhood, loss of ambulation, and reduced life expectancy." },
  { id: "bmd", name: "Becker Muscular Dystrophy", icd10: "G71.01", dsm5: null, category: "Muscular/Physical", description: "A genetic, progressive muscle-wasting condition similar to Duchenne but with later onset and slower progression, characterised by progressive lower limb weakness, fatigue, and reduced endurance." },
  { id: "cp_spastic", name: "Cerebral Palsy — Spastic", icd10: "G80.0", dsm5: null, category: "Muscular/Physical", description: "A group of permanent movement disorders caused by non-progressive damage to the developing brain. Spastic type characterised by increased muscle tone, stiffness, and difficulty with voluntary movement." },
  { id: "cp_dyskinetic", name: "Cerebral Palsy — Dyskinetic", icd10: "G80.3", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy characterised by involuntary, uncontrolled movements (dystonia, athetosis, or chorea) due to damage to the basal ganglia." },
  { id: "cp_ataxic", name: "Cerebral Palsy — Ataxic", icd10: "G80.4", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy characterised by problems with balance and coordination due to damage to the cerebellum." },
  { id: "cp_mixed", name: "Cerebral Palsy — Mixed", icd10: "G80.8", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy involving a combination of spastic, dyskinetic, and/or ataxic features." },
  { id: "sci_para", name: "Spinal Cord Injury — Paraplegia", icd10: "G82.2", dsm5: null, category: "Muscular/Physical", description: "Injury to the spinal cord resulting in impairment or loss of motor and/or sensory function in the lower extremities, affecting mobility, bladder/bowel function, and sensation." },
  { id: "sci_tetra", name: "Spinal Cord Injury — Tetraplegia (Quadriplegia)", icd10: "G82.5", dsm5: null, category: "Muscular/Physical", description: "Injury to the spinal cord resulting in impairment or loss of motor and/or sensory function in all four limbs, trunk, and potentially respiratory function." },
  { id: "spina_bifida", name: "Spina Bifida", icd10: "Q05", dsm5: null, category: "Muscular/Physical", description: "A neural tube defect where the spinal column does not close completely during fetal development, resulting in variable degrees of paralysis, bladder/bowel dysfunction, and hydrocephalus." },
  { id: "fibromyalgia", name: "Fibromyalgia", icd10: "M79.7", dsm5: null, category: "Muscular/Physical", description: "A chronic widespread pain condition characterised by musculoskeletal pain, fatigue, sleep disturbance, cognitive difficulties, and heightened sensitivity to sensory stimuli." },
  { id: "eds", name: "Ehlers-Danlos Syndrome", icd10: "Q79.6", dsm5: null, category: "Muscular/Physical", description: "A group of inherited connective tissue disorders characterised by joint hypermobility, skin hyperextensibility, tissue fragility, chronic pain, and fatigue." },
  { id: "cfs", name: "Chronic Fatigue Syndrome / Myalgic Encephalomyelitis (ME/CFS)", icd10: "G93.32", dsm5: null, category: "Muscular/Physical", description: "A complex, chronic condition characterised by profound fatigue not improved by rest, post-exertional malaise, unrefreshing sleep, cognitive impairment, and orthostatic intolerance." },
  // ─── Genetic / Chromosomal ───
  { id: "down_syndrome", name: "Down Syndrome (Trisomy 21)", icd10: "Q90", dsm5: null, category: "Genetic", description: "A genetic condition caused by the presence of an extra copy of chromosome 21, resulting in intellectual disability, characteristic physical features, and increased risk of associated health conditions." },
  { id: "fragile_x", name: "Fragile X Syndrome", icd10: "Q99.2", dsm5: null, category: "Genetic", description: "A genetic condition caused by a mutation on the X chromosome, the most common inherited cause of intellectual disability, characterised by learning difficulties, behavioural challenges, and distinctive physical features." },
  { id: "prader_willi", name: "Prader-Willi Syndrome", icd10: "Q87.1", dsm5: null, category: "Genetic", description: "A complex genetic condition characterised by hypotonia in infancy, hyperphagia (insatiable appetite), obesity, intellectual disability, behavioural challenges, and short stature." },
  { id: "williams", name: "Williams Syndrome", icd10: "Q93.82", dsm5: null, category: "Genetic", description: "A rare genetic condition characterised by cardiovascular disease, developmental delays, learning challenges, and a distinctive personality including overfriendliness and anxiety." },
  { id: "angelman", name: "Angelman Syndrome", icd10: "Q93.51", dsm5: null, category: "Genetic", description: "A rare genetic condition affecting the nervous system, characterised by severe intellectual disability, speech impairment, movement and balance disorder, and a characteristically happy demeanour with frequent smiling and laughter." },
  { id: "rett", name: "Rett Syndrome", icd10: "F84.2", dsm5: null, category: "Genetic", description: "A rare genetic neurological disorder affecting predominantly females, characterised by normal early development followed by loss of purposeful hand skills, slowed brain and head growth, seizures, and intellectual disability." },
  { id: "22q", name: "22q11.2 Deletion Syndrome (DiGeorge/Velocardiofacial)", icd10: "D82.1", dsm5: null, category: "Genetic", description: "A genetic condition caused by deletion of a small segment of chromosome 22, associated with cardiac anomalies, immune deficiency, palatal abnormalities, learning difficulties, and increased risk of psychotic disorders." },
  // ─── Sensory ───
  { id: "deaf", name: "Sensorineural Hearing Loss — Bilateral", icd10: "H90.3", dsm5: null, category: "Sensory", description: "Permanent hearing loss in both ears caused by damage to the inner ear or auditory nerve, affecting communication, social interaction, and environmental awareness." },
  { id: "blind", name: "Visual Impairment — Legal Blindness", icd10: "H54.0", dsm5: null, category: "Sensory", description: "Visual acuity of 6/60 or less in the better eye with best correction, or a visual field of 10 degrees or less, significantly affecting mobility, daily living tasks, and independence." },
  { id: "deafblind", name: "Deafblindness (Dual Sensory Impairment)", icd10: "H54.0+H90.3", dsm5: null, category: "Sensory", description: "Combined hearing and vision loss that significantly affects communication, access to information, and mobility." },
  // ─── Medical ───
  { id: "diabetes_t1", name: "Type 1 Diabetes Mellitus", icd10: "E10", dsm5: null, category: "Medical", description: "A chronic autoimmune condition in which the pancreas produces little or no insulin, requiring lifelong insulin management, blood glucose monitoring, and dietary management." },
  { id: "copd", name: "Chronic Obstructive Pulmonary Disease (COPD)", icd10: "J44", dsm5: null, category: "Medical", description: "A chronic inflammatory lung disease that causes obstructed airflow from the lungs, characterised by breathing difficulty, cough, mucus production, and reduced exercise tolerance." },
  { id: "rheumatoid", name: "Rheumatoid Arthritis", icd10: "M05", dsm5: null, category: "Medical", description: "A chronic autoimmune inflammatory disorder affecting the joints, causing pain, swelling, stiffness, and progressive joint destruction leading to functional impairment." },
];

export const DIAGNOSIS_CATEGORIES = [...new Set(DIAGNOSIS_LIBRARY.map(d => d.category))].sort();
