export interface DiagnosisEntry {
  id: string;
  name: string;
  icd10: string;
  dsm5: string | null;
  category: string;
  description: string;
  isCustom?: boolean;
}

export interface DiagnosisInstance extends DiagnosisEntry {
  isPrimary?: boolean;
}

export const DIAGNOSIS_LIBRARY: DiagnosisEntry[] = [
  // ═══════════════════════════════════════════
  // NEURODEVELOPMENTAL
  // ═══════════════════════════════════════════
  { id: "asd_1", name: "Autism Spectrum Disorder — Level 1 (Requiring support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "A neurodevelopmental condition characterised by persistent difficulties with social communication and interaction, and restricted, repetitive patterns of behaviour, interests, or activities. Level 1 indicates the individual requires support to function in one or more contexts." },
  { id: "asd_2", name: "Autism Spectrum Disorder — Level 2 (Requiring substantial support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder with marked deficits in verbal and non-verbal social communication, social impairments apparent even with supports in place, and inflexible behaviour that interferes with functioning across contexts." },
  { id: "asd_3", name: "Autism Spectrum Disorder — Level 3 (Requiring very substantial support)", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder with severe deficits in verbal and non-verbal social communication causing severe impairments in functioning, very limited initiation of social interactions, and inflexibility of behaviour that markedly interferes with functioning in all spheres." },
  { id: "asd_unspec", name: "Autism Spectrum Disorder — Unspecified Level", icd10: "F84.0", dsm5: "299.00", category: "Neurodevelopmental", description: "Autism Spectrum Disorder where the level of support required has not yet been formally classified." },
  { id: "aspergers", name: "Asperger's Syndrome (DSM-IV-TR legacy)", icd10: "F84.5", dsm5: "299.80", category: "Neurodevelopmental", description: "Historical diagnostic category characterised by social communication challenges and restricted interests without clinically significant language delay. Now subsumed under Autism Spectrum Disorder in DSM-5; retained for participants holding pre-2013 diagnoses." },
  { id: "pdd_nos", name: "Pervasive Developmental Disorder — Not Otherwise Specified (DSM-IV-TR legacy)", icd10: "F84.9", dsm5: "299.80", category: "Neurodevelopmental", description: "Historical diagnostic category for individuals with severe and pervasive impairment in social interaction or communication who did not meet criteria for other PDDs. Now subsumed under Autism Spectrum Disorder." },
  { id: "adhd_combined", name: "Attention-Deficit/Hyperactivity Disorder — Combined Presentation", icd10: "F90.2", dsm5: "314.01", category: "Neurodevelopmental", description: "A neurodevelopmental disorder characterised by a persistent pattern of inattention and hyperactivity-impulsivity that interferes with functioning or development." },
  { id: "adhd_inattentive", name: "Attention-Deficit/Hyperactivity Disorder — Predominantly Inattentive", icd10: "F90.0", dsm5: "314.00", category: "Neurodevelopmental", description: "ADHD with predominant symptoms of inattention including difficulty sustaining attention, poor organisation, distractibility, and forgetfulness in daily activities." },
  { id: "adhd_hyperactive", name: "Attention-Deficit/Hyperactivity Disorder — Predominantly Hyperactive-Impulsive", icd10: "F90.1", dsm5: "314.01", category: "Neurodevelopmental", description: "ADHD with predominant symptoms of hyperactivity and impulsivity including fidgeting, difficulty remaining seated, excessive talking, and difficulty waiting." },
  { id: "adhd_unspec", name: "Attention-Deficit/Hyperactivity Disorder — Unspecified", icd10: "F90.9", dsm5: "314.01", category: "Neurodevelopmental", description: "ADHD where the specific presentation has not been formally classified, but clinically significant attention and/or hyperactivity-impulsivity impairment is present." },
  { id: "tourette", name: "Tourette's Syndrome", icd10: "F95.2", dsm5: "307.23", category: "Neurodevelopmental", description: "A neurodevelopmental disorder characterised by multiple motor tics and at least one vocal tic, present for more than one year, often co-occurring with ADHD and OCD." },
  { id: "tic_motor", name: "Persistent (Chronic) Motor Tic Disorder", icd10: "F95.1", dsm5: "307.22", category: "Neurodevelopmental", description: "A tic disorder characterised by single or multiple motor tics (but not vocal tics) that persist for more than one year from initial onset." },
  { id: "tic_vocal", name: "Persistent (Chronic) Vocal Tic Disorder", icd10: "F95.1", dsm5: "307.22", category: "Neurodevelopmental", description: "A tic disorder characterised by single or multiple vocal tics (but not motor tics) that persist for more than one year from initial onset." },
  { id: "tic_provisional", name: "Provisional Tic Disorder", icd10: "F95.0", dsm5: "307.21", category: "Neurodevelopmental", description: "Tic disorder with motor and/or vocal tics present for less than one year since first onset." },
  { id: "dcd", name: "Developmental Coordination Disorder (Dyspraxia)", icd10: "F82", dsm5: "315.4", category: "Neurodevelopmental", description: "A neurodevelopmental disorder characterised by motor coordination substantially below that expected for age, resulting in clumsiness, delayed motor milestones, and difficulties with self-care, school performance, and leisure activities." },
  { id: "stereo_movement", name: "Stereotypic Movement Disorder", icd10: "F98.4", dsm5: "307.3", category: "Neurodevelopmental", description: "A disorder characterised by repetitive, driven, and apparently purposeless motor behaviour (e.g., hand-flapping, body-rocking, self-hitting) that interferes with functioning or causes self-injury." },
  { id: "sld_reading", name: "Specific Learning Disorder — With impairment in reading (Dyslexia)", icd10: "F81.0", dsm5: "315.00", category: "Neurodevelopmental", description: "A specific learning disorder affecting reading accuracy, reading rate or fluency, and/or reading comprehension, despite adequate intelligence and educational opportunity." },
  { id: "sld_writing", name: "Specific Learning Disorder — With impairment in written expression (Dysgraphia)", icd10: "F81.81", dsm5: "315.2", category: "Neurodevelopmental", description: "A specific learning disorder affecting spelling accuracy, grammar/punctuation accuracy, and/or clarity or organisation of written expression, despite adequate intelligence and educational opportunity." },
  { id: "sld_math", name: "Specific Learning Disorder — With impairment in mathematics (Dyscalculia)", icd10: "F81.2", dsm5: "315.1", category: "Neurodevelopmental", description: "A specific learning disorder affecting number sense, memorisation of arithmetic facts, accurate or fluent calculation, and/or accurate mathematical reasoning." },
  { id: "sld_mixed", name: "Specific Learning Disorder — Multiple Impairments", icd10: "F81.9", dsm5: "315.9", category: "Neurodevelopmental", description: "A specific learning disorder affecting more than one academic domain (reading, writing, mathematics) in combination." },
  { id: "lang_disorder", name: "Language Disorder (Mixed Receptive-Expressive)", icd10: "F80.2", dsm5: "315.32", category: "Neurodevelopmental", description: "A communication disorder characterised by persistent difficulties in acquiring and using language across modalities due to deficits in comprehension and/or production of vocabulary, sentence structure, and discourse." },
  { id: "expressive_lang", name: "Expressive Language Disorder", icd10: "F80.1", dsm5: "315.31", category: "Neurodevelopmental", description: "A developmental disorder affecting expressive language — limited vocabulary, short sentences, grammatical errors — while receptive language remains relatively preserved." },
  { id: "speech_sound", name: "Speech Sound Disorder", icd10: "F80.0", dsm5: "315.39", category: "Neurodevelopmental", description: "A communication disorder characterised by persistent difficulty with speech sound production that interferes with speech intelligibility or prevents verbal communication." },
  { id: "fluency", name: "Childhood-Onset Fluency Disorder (Stuttering)", icd10: "F80.81", dsm5: "315.35", category: "Neurodevelopmental", description: "A communication disorder characterised by disturbances in the normal fluency and time patterning of speech (repetitions, prolongations, blocks), which causes anxiety about speaking or limits functional communication." },
  { id: "social_comm", name: "Social (Pragmatic) Communication Disorder", icd10: "F80.89", dsm5: "315.39", category: "Neurodevelopmental", description: "A communication disorder involving persistent difficulties in the social use of verbal and non-verbal communication, without the restricted/repetitive behaviours seen in Autism Spectrum Disorder." },
  { id: "apraxia_speech", name: "Childhood Apraxia of Speech", icd10: "F80.9", dsm5: "315.39", category: "Neurodevelopmental", description: "A motor speech disorder where the brain has difficulty planning and programming the movements for speech, resulting in inconsistent errors in consonants and vowels, prosodic disturbance, and speech intelligibility impairment." },
  { id: "fasd", name: "Fetal Alcohol Spectrum Disorder (FASD)", icd10: "Q86.0", dsm5: null, category: "Neurodevelopmental", description: "A range of conditions caused by prenatal alcohol exposure, characterised by physical anomalies, neurocognitive impairment, behavioural difficulties, and adaptive functioning deficits." },
  { id: "gdd", name: "Global Developmental Delay", icd10: "F88", dsm5: "315.8", category: "Neurodevelopmental", description: "A diagnosis for children under 5 years who do not meet expected developmental milestones in several areas of intellectual functioning and where clinical severity cannot yet be reliably assessed." },

  // ═══════════════════════════════════════════
  // INTELLECTUAL DISABILITY
  // ═══════════════════════════════════════════
  { id: "id_mild", name: "Intellectual Disability — Mild", icd10: "F70", dsm5: "317", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 50–69, characterised by slower learning, difficulties with abstract thinking, and reduced adaptive functioning in conceptual, social, and practical domains." },
  { id: "id_moderate", name: "Intellectual Disability — Moderate", icd10: "F71", dsm5: "318.0", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 35–49, characterised by significant delays in development, limited communication skills, and the need for ongoing support with daily living skills." },
  { id: "id_severe", name: "Intellectual Disability — Severe", icd10: "F72", dsm5: "318.1", category: "Intellectual Disability", description: "Intellectual disability with an IQ range of approximately 20–34, characterised by very limited communication, dependence on others for all self-care, and the need for continuous supervision and support." },
  { id: "id_profound", name: "Intellectual Disability — Profound", icd10: "F73", dsm5: "318.2", category: "Intellectual Disability", description: "Intellectual disability with an IQ below 20, characterised by very limited communication and motor function, total dependence on others for all aspects of daily care, and the need for 24-hour support." },
  { id: "id_other", name: "Intellectual Disability — Other Specified", icd10: "F78", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability with associated sensory, motor, or physical impairments preventing formal standardised assessment of severity." },
  { id: "id_unspec", name: "Intellectual Disability — Unspecified", icd10: "F79", dsm5: "319", category: "Intellectual Disability", description: "Intellectual disability where the severity level has not been formally determined but significant deficits in intellectual and adaptive functioning are present." },
  { id: "borderline_if", name: "Borderline Intellectual Functioning", icd10: "R41.83", dsm5: "V62.89", category: "Intellectual Disability", description: "Borderline cognitive functioning (IQ approximately 71–84) that does not meet criteria for Intellectual Disability but is associated with adaptive difficulties across conceptual, social, and practical domains." },

  // ═══════════════════════════════════════════
  // PSYCHOSOCIAL — MOOD & PSYCHOTIC
  // ═══════════════════════════════════════════
  { id: "mdd_single", name: "Major Depressive Disorder — Single Episode", icd10: "F32.9", dsm5: "296.2x", category: "Psychosocial", description: "A mood disorder characterised by a single episode of persistent low mood, loss of interest or pleasure, and associated symptoms including fatigue, sleep disturbance, appetite changes, and difficulty concentrating." },
  { id: "mdd_recurrent", name: "Major Depressive Disorder — Recurrent", icd10: "F33.9", dsm5: "296.3x", category: "Psychosocial", description: "A mood disorder with recurrent episodes of persistent depressed mood, loss of interest, and associated symptoms, with a pattern of relapse and recovery." },
  { id: "mdd_psychotic", name: "Major Depressive Disorder — With Psychotic Features", icd10: "F32.3", dsm5: "296.24", category: "Psychosocial", description: "Major depressive disorder accompanied by hallucinations or delusions, typically mood-congruent themes of guilt, worthlessness, or nihilism." },
  { id: "pdd_dysthymia", name: "Persistent Depressive Disorder (Dysthymia)", icd10: "F34.1", dsm5: "300.4", category: "Psychosocial", description: "A chronic mood disorder characterised by depressed mood occurring for most of the day, for more days than not, for at least two years in adults (one year in children/adolescents)." },
  { id: "dmdd", name: "Disruptive Mood Dysregulation Disorder", icd10: "F34.81", dsm5: "296.99", category: "Psychosocial", description: "A childhood-onset mood disorder characterised by severe, recurrent temper outbursts grossly out of proportion to the situation, with persistent irritable or angry mood between outbursts." },
  { id: "pmdd", name: "Premenstrual Dysphoric Disorder", icd10: "N94.3", dsm5: "625.4", category: "Psychosocial", description: "A mood disorder characterised by significant mood lability, irritability, depressed mood, and anxiety in the week before menses, which interferes with functioning." },
  { id: "bpad_1", name: "Bipolar I Disorder", icd10: "F31.1", dsm5: "296.4x", category: "Psychosocial", description: "A mood disorder characterised by at least one manic episode, which may be preceded or followed by hypomanic or major depressive episodes. Manic episodes involve persistently elevated, expansive, or irritable mood with increased energy." },
  { id: "bpad_2", name: "Bipolar II Disorder", icd10: "F31.81", dsm5: "296.89", category: "Psychosocial", description: "A mood disorder characterised by at least one hypomanic episode and at least one major depressive episode, without a full manic episode." },
  { id: "cyclothymic", name: "Cyclothymic Disorder", icd10: "F34.0", dsm5: "301.13", category: "Psychosocial", description: "A chronic, fluctuating mood disturbance with numerous periods of hypomanic and depressive symptoms over at least two years that do not meet criteria for full hypomanic or major depressive episodes." },
  { id: "bpad_unspec", name: "Bipolar Disorder — Unspecified", icd10: "F31.9", dsm5: "296.80", category: "Psychosocial", description: "Bipolar spectrum disorder not meeting full criteria for Bipolar I, Bipolar II, or Cyclothymic Disorder, with mood symptoms causing functional impairment." },
  { id: "schizophrenia", name: "Schizophrenia", icd10: "F20.9", dsm5: "295.90", category: "Psychosocial", description: "A chronic psychotic disorder characterised by disturbances in thought, perception, and behaviour, including hallucinations, delusions, disorganised speech, and negative symptoms such as reduced emotional expression." },
  { id: "schizo_paranoid", name: "Schizophrenia — Paranoid Type (ICD-10)", icd10: "F20.0", dsm5: "295.30", category: "Psychosocial", description: "Schizophrenia predominantly characterised by paranoid delusions and auditory hallucinations, with relatively preserved cognitive functioning and affect." },
  { id: "schizophreniform", name: "Schizophreniform Disorder", icd10: "F20.81", dsm5: "295.40", category: "Psychosocial", description: "A psychotic disorder with symptoms identical to schizophrenia but lasting between one and six months." },
  { id: "schizoaffective", name: "Schizoaffective Disorder", icd10: "F25.9", dsm5: "295.70", category: "Psychosocial", description: "A disorder characterised by a combination of schizophrenia symptoms (hallucinations, delusions) and mood disorder symptoms (depression or mania)." },
  { id: "sad_bipolar", name: "Schizoaffective Disorder — Bipolar Type", icd10: "F25.0", dsm5: "295.70", category: "Psychosocial", description: "Schizoaffective disorder where the mood component includes manic or mixed episodes, possibly alongside depressive episodes." },
  { id: "sad_depressive", name: "Schizoaffective Disorder — Depressive Type", icd10: "F25.1", dsm5: "295.70", category: "Psychosocial", description: "Schizoaffective disorder where the mood component consists only of major depressive episodes." },
  { id: "brief_psychotic", name: "Brief Psychotic Disorder", icd10: "F23", dsm5: "298.8", category: "Psychosocial", description: "A psychotic disorder with sudden onset of one or more positive psychotic symptoms (delusions, hallucinations, disorganised speech/behaviour) lasting less than one month with full return to premorbid functioning." },
  { id: "delusional", name: "Delusional Disorder", icd10: "F22", dsm5: "297.1", category: "Psychosocial", description: "A psychotic disorder characterised by one or more delusions for at least one month, without other active-phase symptoms of schizophrenia, and with relatively preserved functioning outside the delusion's direct impact." },
  { id: "substance_psych", name: "Substance/Medication-Induced Psychotic Disorder", icd10: "F19.959", dsm5: "292.9", category: "Psychosocial", description: "Psychotic symptoms (delusions or hallucinations) that develop during or soon after intoxication or withdrawal from a substance, or after exposure to a medication." },
  { id: "psychotic_nos", name: "Unspecified Psychotic Disorder", icd10: "F29", dsm5: "298.9", category: "Psychosocial", description: "Symptoms characteristic of a psychotic disorder that cause clinically significant impairment but do not meet full criteria for any specific psychotic disorder." },
  { id: "did", name: "Dissociative Identity Disorder", icd10: "F44.81", dsm5: "300.14", category: "Psychosocial", description: "A dissociative disorder characterised by the presence of two or more distinct personality states, with recurrent gaps in recall of everyday events, personal information, or traumatic events." },
  { id: "depersonalisation", name: "Depersonalisation/Derealisation Disorder", icd10: "F48.1", dsm5: "300.6", category: "Psychosocial", description: "A dissociative disorder characterised by persistent or recurrent experiences of depersonalisation (detachment from self) and/or derealisation (detachment from surroundings) with intact reality testing." },

  // ═══════════════════════════════════════════
  // ANXIETY & OCD-SPECTRUM
  // ═══════════════════════════════════════════
  { id: "gad", name: "Generalised Anxiety Disorder", icd10: "F41.1", dsm5: "300.02", category: "Anxiety", description: "An anxiety disorder characterised by excessive, persistent worry about a range of everyday concerns that is difficult to control and causes significant distress or impairment." },
  { id: "social_anx", name: "Social Anxiety Disorder (Social Phobia)", icd10: "F40.10", dsm5: "300.23", category: "Anxiety", description: "An anxiety disorder characterised by marked fear or anxiety about social situations in which the individual may be exposed to scrutiny by others." },
  { id: "panic", name: "Panic Disorder", icd10: "F41.0", dsm5: "300.01", category: "Anxiety", description: "An anxiety disorder characterised by recurrent, unexpected panic attacks with intense physical symptoms including heart palpitations, shortness of breath, and fear of losing control." },
  { id: "agoraphobia", name: "Agoraphobia", icd10: "F40.00", dsm5: "300.22", category: "Anxiety", description: "An anxiety disorder characterised by marked fear or anxiety about situations where escape might be difficult, such as public transport, open spaces, enclosed spaces, crowds, or being outside the home alone." },
  { id: "specific_phobia", name: "Specific Phobia", icd10: "F40.2", dsm5: "300.29", category: "Anxiety", description: "An anxiety disorder characterised by marked fear or anxiety about a specific object or situation (e.g., animals, heights, medical procedures, flying), which is actively avoided or endured with intense distress." },
  { id: "separation_anx", name: "Separation Anxiety Disorder", icd10: "F93.0", dsm5: "309.21", category: "Anxiety", description: "An anxiety disorder characterised by developmentally inappropriate and excessive fear or anxiety concerning separation from attachment figures." },
  { id: "selective_mutism", name: "Selective Mutism", icd10: "F94.0", dsm5: "313.23", category: "Anxiety", description: "A consistent failure to speak in specific social situations where speaking is expected (e.g., school), despite speaking in other situations (typically at home)." },
  { id: "ocd", name: "Obsessive-Compulsive Disorder", icd10: "F42.2", dsm5: "300.3", category: "Anxiety", description: "A disorder characterised by recurrent, intrusive obsessions and/or repetitive compulsive behaviours that are time-consuming and cause significant distress or functional impairment." },
  { id: "bdd", name: "Body Dysmorphic Disorder", icd10: "F45.22", dsm5: "300.7", category: "Anxiety", description: "A disorder characterised by preoccupation with one or more perceived defects in physical appearance that are not observable to others, leading to repetitive behaviours and significant distress." },
  { id: "hoarding", name: "Hoarding Disorder", icd10: "F42.3", dsm5: "300.3", category: "Anxiety", description: "A disorder characterised by persistent difficulty discarding possessions regardless of value, resulting in accumulation that congests living areas and compromises their intended use." },
  { id: "trichotillomania", name: "Trichotillomania (Hair-Pulling Disorder)", icd10: "F63.3", dsm5: "312.39", category: "Anxiety", description: "A body-focused repetitive behaviour characterised by recurrent hair-pulling resulting in hair loss, with repeated attempts to stop." },
  { id: "excoriation", name: "Excoriation (Skin-Picking) Disorder", icd10: "L98.1", dsm5: "698.4", category: "Anxiety", description: "A body-focused repetitive behaviour characterised by recurrent skin-picking resulting in lesions, with repeated attempts to stop." },
  { id: "anxiety_nos", name: "Unspecified Anxiety Disorder", icd10: "F41.9", dsm5: "300.00", category: "Anxiety", description: "Clinically significant anxiety symptoms causing distress or impairment that do not meet full criteria for any specific anxiety disorder." },

  // ═══════════════════════════════════════════
  // TRAUMA & STRESSOR-RELATED
  // ═══════════════════════════════════════════
  { id: "ptsd", name: "Post-Traumatic Stress Disorder", icd10: "F43.10", dsm5: "309.81", category: "Trauma", description: "A disorder that develops following exposure to a traumatic event, characterised by intrusive re-experiencing, avoidance of trauma-related stimuli, negative alterations in cognition and mood, and marked alterations in arousal and reactivity." },
  { id: "cptsd", name: "Complex Post-Traumatic Stress Disorder (ICD-11)", icd10: "6B41", dsm5: null, category: "Trauma", description: "A condition arising from prolonged, repeated trauma characterised by PTSD symptoms plus disturbances in self-organisation including affect dysregulation, negative self-concept, and difficulties in relationships." },
  { id: "acute_stress", name: "Acute Stress Disorder", icd10: "F43.0", dsm5: "308.3", category: "Trauma", description: "A stress-related disorder with PTSD-like symptoms (intrusion, dissociation, avoidance, arousal) occurring 3 days to 1 month after trauma exposure." },
  { id: "adj_depressed", name: "Adjustment Disorder — With Depressed Mood", icd10: "F43.21", dsm5: "309.0", category: "Trauma", description: "A stress-response disorder with predominantly low mood, tearfulness, and hopelessness developing within 3 months of an identifiable stressor." },
  { id: "adj_anxious", name: "Adjustment Disorder — With Anxiety", icd10: "F43.22", dsm5: "309.24", category: "Trauma", description: "A stress-response disorder with predominantly nervousness, worry, jitteriness, or separation anxiety developing in response to an identifiable stressor." },
  { id: "adj_mixed", name: "Adjustment Disorder — With Mixed Anxiety and Depressed Mood", icd10: "F43.23", dsm5: "309.28", category: "Trauma", description: "A stress-response disorder with a combination of depression and anxiety symptoms developing in response to an identifiable stressor." },
  { id: "adj_conduct", name: "Adjustment Disorder — With Disturbance of Conduct", icd10: "F43.24", dsm5: "309.3", category: "Trauma", description: "A stress-response disorder with predominant behavioural disturbance (e.g., truancy, fighting, reckless driving) in response to an identifiable stressor." },
  { id: "rad", name: "Reactive Attachment Disorder", icd10: "F94.1", dsm5: "313.89", category: "Trauma", description: "A childhood disorder arising from severe neglect or repeated changes of caregivers, characterised by markedly disturbed, developmentally inappropriate attachment behaviours and withdrawal from caregivers." },
  { id: "dsed", name: "Disinhibited Social Engagement Disorder", icd10: "F94.2", dsm5: "313.89", category: "Trauma", description: "A childhood disorder arising from early social neglect, characterised by overly familiar behaviour with unfamiliar adults, reduced checking back with caregivers, and willingness to go off with strangers." },
  { id: "prolonged_grief", name: "Prolonged Grief Disorder", icd10: "F43.81", dsm5: "309.89", category: "Trauma", description: "A persistent, pervasive grief response following the death of a close person, with intense yearning, preoccupation, and functional impairment extending beyond normative cultural grieving periods." },

  // ═══════════════════════════════════════════
  // PERSONALITY DISORDERS
  // ═══════════════════════════════════════════
  { id: "paranoid_pd", name: "Paranoid Personality Disorder (Cluster A)", icd10: "F60.0", dsm5: "301.0", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of distrust and suspiciousness of others, interpreting their motives as malevolent, beginning by early adulthood." },
  { id: "schizoid_pd", name: "Schizoid Personality Disorder (Cluster A)", icd10: "F60.1", dsm5: "301.20", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of detachment from social relationships and a restricted range of emotional expression in interpersonal settings." },
  { id: "schizotypal_pd", name: "Schizotypal Personality Disorder (Cluster A)", icd10: "F21", dsm5: "301.22", category: "Personality", description: "A personality disorder characterised by acute discomfort with close relationships, cognitive or perceptual distortions, and eccentricities of behaviour, beginning by early adulthood." },
  { id: "bpd", name: "Borderline Personality Disorder (Cluster B)", icd10: "F60.3", dsm5: "301.83", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of instability in interpersonal relationships, self-image, and affect, with marked impulsivity including self-harm and suicidal behaviour." },
  { id: "eupd", name: "Emotionally Unstable Personality Disorder (ICD-10)", icd10: "F60.3", dsm5: null, category: "Personality", description: "ICD-10 equivalent of Borderline Personality Disorder, characterised by emotional instability, impulsive behaviour, and difficulties maintaining stable relationships." },
  { id: "antisocial_pd", name: "Antisocial Personality Disorder (Cluster B)", icd10: "F60.2", dsm5: "301.7", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of disregard for, and violation of, the rights of others, beginning in childhood or early adolescence and continuing into adulthood." },
  { id: "histrionic_pd", name: "Histrionic Personality Disorder (Cluster B)", icd10: "F60.4", dsm5: "301.50", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of excessive emotionality and attention-seeking, beginning by early adulthood." },
  { id: "narcissistic_pd", name: "Narcissistic Personality Disorder (Cluster B)", icd10: "F60.81", dsm5: "301.81", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of grandiosity (in fantasy or behaviour), need for admiration, and lack of empathy, beginning by early adulthood." },
  { id: "avoidant_pd", name: "Avoidant Personality Disorder (Cluster C)", icd10: "F60.6", dsm5: "301.82", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of social inhibition, feelings of inadequacy, and hypersensitivity to negative evaluation, beginning by early adulthood." },
  { id: "dependent_pd", name: "Dependent Personality Disorder (Cluster C)", icd10: "F60.7", dsm5: "301.6", category: "Personality", description: "A personality disorder characterised by a pervasive and excessive need to be taken care of that leads to submissive and clinging behaviour and fears of separation." },
  { id: "ocpd", name: "Obsessive-Compulsive Personality Disorder (Cluster C)", icd10: "F60.5", dsm5: "301.4", category: "Personality", description: "A personality disorder characterised by a pervasive pattern of preoccupation with orderliness, perfectionism, and mental and interpersonal control, at the expense of flexibility, openness, and efficiency." },
  { id: "pd_nos", name: "Personality Disorder — Unspecified", icd10: "F60.9", dsm5: "301.9", category: "Personality", description: "Clinically significant personality-functioning impairment that does not meet full criteria for any specific personality disorder." },

  // ═══════════════════════════════════════════
  // BEHAVIOUR & CONDUCT
  // ═══════════════════════════════════════════
  { id: "odd", name: "Oppositional Defiant Disorder", icd10: "F91.3", dsm5: "313.81", category: "Behaviour & Conduct", description: "A childhood behavioural disorder characterised by a pattern of angry/irritable mood, argumentative/defiant behaviour, and/or vindictiveness lasting at least 6 months." },
  { id: "conduct_childhood", name: "Conduct Disorder — Childhood Onset", icd10: "F91.1", dsm5: "312.81", category: "Behaviour & Conduct", description: "A repetitive and persistent pattern of behaviour violating the rights of others or major age-appropriate societal norms, with onset before age 10." },
  { id: "conduct_adolescent", name: "Conduct Disorder — Adolescent Onset", icd10: "F91.2", dsm5: "312.82", category: "Behaviour & Conduct", description: "A repetitive and persistent pattern of behaviour violating the rights of others or major age-appropriate societal norms, with onset after age 10." },
  { id: "conduct_unspec", name: "Conduct Disorder — Unspecified Onset", icd10: "F91.9", dsm5: "312.89", category: "Behaviour & Conduct", description: "Conduct disorder where the age of onset is unknown but criteria for the disorder are otherwise met." },
  { id: "ied", name: "Intermittent Explosive Disorder", icd10: "F63.81", dsm5: "312.34", category: "Behaviour & Conduct", description: "A disorder characterised by recurrent behavioural outbursts representing a failure to control aggressive impulses, grossly out of proportion to provocation." },
  { id: "kleptomania", name: "Kleptomania", icd10: "F63.2", dsm5: "312.32", category: "Behaviour & Conduct", description: "An impulse-control disorder characterised by recurrent failure to resist impulses to steal objects that are not needed for personal use or monetary value." },
  { id: "pyromania", name: "Pyromania", icd10: "F63.1", dsm5: "312.33", category: "Behaviour & Conduct", description: "An impulse-control disorder characterised by deliberate and purposeful fire-setting on more than one occasion, with tension or affective arousal before the act and relief afterwards." },

  // ═══════════════════════════════════════════
  // SUBSTANCE USE
  // ═══════════════════════════════════════════
  { id: "aud", name: "Alcohol Use Disorder", icd10: "F10.20", dsm5: "303.90", category: "Substance Use", description: "A problematic pattern of alcohol use leading to clinically significant impairment or distress, characterised by impaired control, social impairment, risky use, and pharmacological criteria (tolerance, withdrawal)." },
  { id: "opioid_ud", name: "Opioid Use Disorder", icd10: "F11.20", dsm5: "304.00", category: "Substance Use", description: "A problematic pattern of opioid use (prescribed or illicit) leading to clinically significant impairment, characterised by craving, unsuccessful efforts to reduce use, and physiological dependence." },
  { id: "stimulant_ud", name: "Stimulant Use Disorder (Amphetamine/Methamphetamine/Cocaine)", icd10: "F15.20", dsm5: "304.40", category: "Substance Use", description: "A problematic pattern of stimulant use leading to clinically significant impairment, with characteristic intoxication, withdrawal, and pattern of compulsive use." },
  { id: "cannabis_ud", name: "Cannabis Use Disorder", icd10: "F12.20", dsm5: "305.20", category: "Substance Use", description: "A problematic pattern of cannabis use leading to clinically significant impairment or distress, with characteristic withdrawal syndrome and functional consequences." },
  { id: "sedative_ud", name: "Sedative/Hypnotic/Anxiolytic Use Disorder", icd10: "F13.20", dsm5: "304.10", category: "Substance Use", description: "A problematic pattern of sedative, hypnotic, or anxiolytic (e.g., benzodiazepine) use leading to clinically significant impairment." },
  { id: "tobacco_ud", name: "Tobacco Use Disorder", icd10: "F17.200", dsm5: "305.1", category: "Substance Use", description: "A problematic pattern of tobacco use leading to clinically significant impairment, with characteristic withdrawal and continued use despite medical consequences." },
  { id: "inhalant_ud", name: "Inhalant Use Disorder", icd10: "F18.20", dsm5: "304.60", category: "Substance Use", description: "A problematic pattern of inhalant use (e.g., volatile solvents) leading to clinically significant impairment; common neurocognitive sequelae." },
  { id: "hallucinogen_ud", name: "Hallucinogen Use Disorder", icd10: "F16.20", dsm5: "304.50", category: "Substance Use", description: "A problematic pattern of hallucinogen use (e.g., LSD, psilocybin, MDMA) leading to clinically significant impairment, with possible persistent perception disorder." },
  { id: "gambling", name: "Gambling Disorder", icd10: "F63.0", dsm5: "312.31", category: "Substance Use", description: "A behavioural addiction characterised by persistent and recurrent problematic gambling behaviour leading to clinically significant impairment or distress." },
  { id: "polysubstance", name: "Other (or Unknown) Substance Use Disorder", icd10: "F19.20", dsm5: "304.90", category: "Substance Use", description: "A problematic pattern of use of one or more substances not otherwise classified, or of substances where the specific agent is unknown." },

  // ═══════════════════════════════════════════
  // SLEEP DISORDERS
  // ═══════════════════════════════════════════
  { id: "insomnia", name: "Insomnia Disorder", icd10: "F51.01", dsm5: "780.52", category: "Sleep Disorders", description: "A predominant complaint of dissatisfaction with sleep quantity or quality (difficulty initiating sleep, maintaining sleep, or early-morning awakening) causing significant distress or impairment." },
  { id: "hypersomnia", name: "Hypersomnolence Disorder", icd10: "F51.11", dsm5: "780.54", category: "Sleep Disorders", description: "Excessive sleepiness despite a main sleep period of at least 7 hours, with recurrent lapses into sleep during the day, prolonged non-restorative sleep, or difficulty being fully awake after abrupt awakening." },
  { id: "narcolepsy", name: "Narcolepsy", icd10: "G47.4", dsm5: "347.00", category: "Sleep Disorders", description: "A chronic neurological sleep disorder characterised by excessive daytime sleepiness, cataplexy, sleep paralysis, and hypnagogic hallucinations." },
  { id: "osa", name: "Obstructive Sleep Apnoea Hypopnoea", icd10: "G47.33", dsm5: "327.23", category: "Sleep Disorders", description: "A breathing-related sleep disorder with repeated episodes of upper-airway obstruction during sleep, causing fragmented sleep, daytime fatigue, and cardiovascular consequences." },
  { id: "central_sa", name: "Central Sleep Apnoea", icd10: "G47.31", dsm5: "327.21", category: "Sleep Disorders", description: "A breathing-related sleep disorder caused by variable effort in breathing during sleep due to central nervous system dysfunction." },
  { id: "circadian", name: "Circadian Rhythm Sleep-Wake Disorder", icd10: "G47.20", dsm5: "327.30", category: "Sleep Disorders", description: "A persistent or recurrent pattern of sleep disruption due to alteration of the circadian system or misalignment between the endogenous circadian rhythm and the sleep-wake schedule required." },
  { id: "rls", name: "Restless Legs Syndrome", icd10: "G25.81", dsm5: "333.94", category: "Sleep Disorders", description: "A sensorimotor disorder characterised by an urge to move the legs, usually accompanied by uncomfortable sensations, which begins or worsens during rest and is relieved by movement." },
  { id: "parasomnia", name: "Non-REM Sleep Arousal Disorders (Sleepwalking/Night Terrors)", icd10: "F51.3", dsm5: "307.46", category: "Sleep Disorders", description: "Recurrent episodes of incomplete awakening from sleep, usually from deep sleep stages, manifesting as sleepwalking or sleep terrors." },
  { id: "rbd", name: "REM Sleep Behaviour Disorder", icd10: "G47.52", dsm5: "327.42", category: "Sleep Disorders", description: "A parasomnia characterised by repeated episodes of arousal during REM sleep associated with vocalisation and/or complex motor behaviours, often enacting dream content." },

  // ═══════════════════════════════════════════
  // EATING & FEEDING
  // ═══════════════════════════════════════════
  { id: "eating_an", name: "Anorexia Nervosa", icd10: "F50.0", dsm5: "307.1", category: "Eating & Feeding", description: "An eating disorder characterised by restriction of energy intake, intense fear of gaining weight, and disturbance in body image, leading to significantly low body weight." },
  { id: "eating_bn", name: "Bulimia Nervosa", icd10: "F50.2", dsm5: "307.51", category: "Eating & Feeding", description: "An eating disorder characterised by recurrent episodes of binge eating followed by compensatory behaviours such as self-induced vomiting, laxative misuse, or excessive exercise." },
  { id: "bed", name: "Binge Eating Disorder", icd10: "F50.81", dsm5: "307.51", category: "Eating & Feeding", description: "An eating disorder characterised by recurrent episodes of binge eating without regular compensatory behaviours, causing significant distress." },
  { id: "arfid", name: "Avoidant/Restrictive Food Intake Disorder (ARFID)", icd10: "F50.82", dsm5: "307.59", category: "Eating & Feeding", description: "A feeding disorder characterised by failure to meet appropriate nutritional and/or energy needs due to avoidance based on sensory characteristics, lack of interest, or fear of aversive consequences — without body-image disturbance." },
  { id: "pica", name: "Pica", icd10: "F50.8", dsm5: "307.52", category: "Eating & Feeding", description: "A feeding disorder characterised by persistent eating of non-nutritive, non-food substances (e.g., paper, soap, hair, soil) over at least one month, inappropriate to developmental level." },
  { id: "rumination", name: "Rumination Disorder", icd10: "F98.21", dsm5: "307.53", category: "Eating & Feeding", description: "Repeated regurgitation of food for at least one month, which may be re-chewed, re-swallowed, or spit out; not attributable to an associated gastrointestinal or medical condition." },
  { id: "osfed", name: "Other Specified Feeding or Eating Disorder (OSFED)", icd10: "F50.89", dsm5: "307.59", category: "Eating & Feeding", description: "Clinically significant eating-disorder symptoms that cause distress or impairment but do not meet full criteria for any specific eating disorder (e.g., atypical anorexia, purging disorder)." },

  // ═══════════════════════════════════════════
  // ACQUIRED BRAIN INJURY
  // ═══════════════════════════════════════════
  { id: "tbi_mild", name: "Traumatic Brain Injury — Mild (Concussion)", icd10: "S06.0", dsm5: null, category: "Acquired Brain Injury", description: "Mild traumatic brain injury from an external mechanical force, with brief loss of consciousness (<30 min), post-traumatic amnesia <24 hours, and initial GCS 13–15." },
  { id: "tbi_moderate", name: "Traumatic Brain Injury — Moderate", icd10: "S06.2", dsm5: null, category: "Acquired Brain Injury", description: "Moderate traumatic brain injury with loss of consciousness 30 minutes to 24 hours, post-traumatic amnesia 1–7 days, and initial GCS 9–12, causing persistent cognitive, physical, and psychosocial impairment." },
  { id: "tbi_severe", name: "Traumatic Brain Injury — Severe", icd10: "S06.3", dsm5: null, category: "Acquired Brain Injury", description: "Severe traumatic brain injury with loss of consciousness >24 hours, post-traumatic amnesia >7 days, or GCS <9, resulting in significant long-term cognitive, physical, and behavioural impairment." },
  { id: "abi_anoxic", name: "Acquired Brain Injury — Anoxic/Hypoxic", icd10: "G93.1", dsm5: null, category: "Acquired Brain Injury", description: "Brain injury resulting from insufficient oxygen supply to the brain (e.g., cardiac arrest, near-drowning, overdose), causing diffuse damage to cognitive, physical, and behavioural functions." },
  { id: "abi_tumour", name: "Acquired Brain Injury — Post Brain Tumour", icd10: "D49.6", dsm5: null, category: "Acquired Brain Injury", description: "Cognitive and physical sequelae following primary or secondary brain tumour or its treatment (surgery, radiation, chemotherapy), with location-dependent impairments." },
  { id: "abi_infection", name: "Acquired Brain Injury — Post Encephalitis/Meningitis", icd10: "G09", dsm5: null, category: "Acquired Brain Injury", description: "Residual cognitive, motor, sensory, or behavioural impairment following central nervous system infection (viral or bacterial encephalitis, meningitis)." },
  { id: "abi_toxic", name: "Acquired Brain Injury — Toxic/Metabolic", icd10: "G93.4", dsm5: null, category: "Acquired Brain Injury", description: "Brain injury caused by toxic exposure (e.g., chronic alcohol, carbon monoxide, heavy metals) or metabolic derangement (e.g., hepatic encephalopathy), with diffuse cognitive and motor consequences." },

  // ═══════════════════════════════════════════
  // NEUROLOGICAL
  // ═══════════════════════════════════════════
  { id: "stroke_left", name: "Cerebrovascular Accident (Stroke) — Left Hemisphere", icd10: "I63.9", dsm5: null, category: "Neurological", description: "A stroke affecting the left hemisphere of the brain, commonly resulting in right-sided weakness or paralysis, speech and language difficulties (aphasia), and cognitive impairments." },
  { id: "stroke_right", name: "Cerebrovascular Accident (Stroke) — Right Hemisphere", icd10: "I63.9", dsm5: null, category: "Neurological", description: "A stroke affecting the right hemisphere of the brain, commonly resulting in left-sided weakness or paralysis, spatial awareness difficulties, neglect, and changes to perception and behaviour." },
  { id: "stroke_brainstem", name: "Cerebrovascular Accident — Brainstem", icd10: "I63.9", dsm5: null, category: "Neurological", description: "Stroke affecting the brainstem, commonly producing cranial nerve palsies, dysphagia, dysarthria, vertigo, ataxia, and variable sensorimotor involvement." },
  { id: "stroke_cerebellar", name: "Cerebrovascular Accident — Cerebellar", icd10: "I63.9", dsm5: null, category: "Neurological", description: "Stroke affecting the cerebellum, commonly resulting in ataxia, balance disturbance, intention tremor, and coordination difficulties." },
  { id: "ms_rr", name: "Multiple Sclerosis — Relapsing-Remitting", icd10: "G35", dsm5: null, category: "Neurological", description: "MS subtype with discrete clinical attacks (relapses) causing new or worsened symptoms, followed by periods of partial or complete recovery; most common MS presentation." },
  { id: "ms_sp", name: "Multiple Sclerosis — Secondary Progressive", icd10: "G35", dsm5: null, category: "Neurological", description: "MS subtype evolving from initial relapsing-remitting disease into progressive accumulation of disability with or without continued relapses." },
  { id: "ms_pp", name: "Multiple Sclerosis — Primary Progressive", icd10: "G35", dsm5: null, category: "Neurological", description: "MS subtype with progressive accumulation of disability from disease onset, without discrete relapses; less common and typically later-onset." },
  { id: "parkinsons", name: "Parkinson's Disease", icd10: "G20", dsm5: null, category: "Neurological", description: "A progressive neurodegenerative disorder characterised by tremor, rigidity, bradykinesia, and postural instability, with associated non-motor symptoms including cognitive decline and mood disturbance." },
  { id: "parkinsons_plus", name: "Parkinson's Plus Syndromes (PSP/MSA/CBD)", icd10: "G23.1", dsm5: null, category: "Neurological", description: "A group of neurodegenerative disorders with parkinsonism plus additional features: progressive supranuclear palsy, multiple system atrophy, corticobasal degeneration. Typically faster progression and poorer levodopa response than Parkinson's disease." },
  { id: "mnd", name: "Motor Neurone Disease (ALS)", icd10: "G12.21", dsm5: null, category: "Neurological", description: "A progressive, fatal neurodegenerative disease affecting motor neurones, leading to progressive muscle weakness, wasting, and eventually loss of voluntary movement, speech, swallowing, and breathing." },
  { id: "huntingtons", name: "Huntington's Disease", icd10: "G10", dsm5: null, category: "Neurological", description: "A hereditary, progressive neurodegenerative disorder characterised by involuntary movements (chorea), cognitive decline, and psychiatric disturbance." },
  { id: "epilepsy", name: "Epilepsy — Unspecified", icd10: "G40.909", dsm5: null, category: "Neurological", description: "A chronic neurological condition characterised by recurrent, unprovoked seizures due to abnormal electrical activity in the brain." },
  { id: "epilepsy_gen", name: "Generalised Epilepsy", icd10: "G40.309", dsm5: null, category: "Neurological", description: "Epilepsy involving seizures that begin in both cerebral hemispheres simultaneously (e.g., tonic-clonic, absence, myoclonic)." },
  { id: "epilepsy_focal", name: "Focal (Partial) Epilepsy", icd10: "G40.209", dsm5: null, category: "Neurological", description: "Epilepsy involving seizures that begin in one area of the brain, with or without impaired awareness and with or without secondary generalisation." },
  { id: "lennox_gastaut", name: "Lennox-Gastaut Syndrome", icd10: "G40.812", dsm5: null, category: "Neurological", description: "A severe childhood-onset epilepsy syndrome characterised by multiple seizure types, intellectual disability, and a distinctive slow spike-and-wave EEG pattern; highly treatment-resistant." },
  { id: "dravet", name: "Dravet Syndrome", icd10: "G40.83", dsm5: null, category: "Neurological", description: "A severe early-infancy-onset epileptic encephalopathy with prolonged febrile seizures, later multiple seizure types, developmental regression, and intellectual disability." },
  { id: "dystonia", name: "Dystonia", icd10: "G24.9", dsm5: null, category: "Neurological", description: "A movement disorder characterised by sustained or intermittent muscle contractions causing abnormal movements and/or postures, which may be focal, segmental, multifocal, or generalised." },
  { id: "essential_tremor", name: "Essential Tremor", icd10: "G25.0", dsm5: null, category: "Neurological", description: "A common movement disorder characterised by involuntary rhythmic shaking, most commonly of the hands, worsened by action; may affect head, voice, or legs." },
  { id: "gbs", name: "Guillain-Barré Syndrome", icd10: "G61.0", dsm5: null, category: "Neurological", description: "An acute autoimmune demyelinating polyneuropathy causing rapidly progressive ascending muscle weakness and areflexia, often with residual neurological deficits." },
  { id: "myasthenia_gravis", name: "Myasthenia Gravis", icd10: "G70.00", dsm5: null, category: "Neurological", description: "An autoimmune neuromuscular disorder characterised by fluctuating muscle weakness and fatigability, particularly affecting ocular, bulbar, and proximal limb muscles." },
  { id: "nf1", name: "Neurofibromatosis Type 1", icd10: "Q85.01", dsm5: null, category: "Neurological", description: "A genetic disorder characterised by multiple café-au-lait macules, skinfold freckling, neurofibromas, Lisch nodules, optic pathway gliomas, and variable cognitive involvement." },
  { id: "nf2", name: "Neurofibromatosis Type 2", icd10: "Q85.02", dsm5: null, category: "Neurological", description: "A genetic disorder characterised primarily by bilateral vestibular schwannomas causing progressive hearing loss, balance disturbance, and other nervous-system tumours." },
  { id: "tuberous_sclerosis", name: "Tuberous Sclerosis Complex", icd10: "Q85.1", dsm5: null, category: "Neurological", description: "A genetic disorder causing benign tumours in multiple organ systems; neurological manifestations include epilepsy, intellectual disability, autism, and characteristic cortical tubers." },
  { id: "hsp", name: "Hereditary Spastic Paraplegia", icd10: "G11.4", dsm5: null, category: "Neurological", description: "A group of inherited disorders characterised by progressive lower-limb spasticity and weakness due to degeneration of corticospinal tracts." },
  { id: "friedreich_ataxia", name: "Friedreich's Ataxia", icd10: "G11.11", dsm5: null, category: "Neurological", description: "A progressive autosomal recessive neurodegenerative disorder with gait and limb ataxia, dysarthria, cardiomyopathy, scoliosis, and diabetes." },

  // ═══════════════════════════════════════════
  // DEMENTIA & NEUROCOGNITIVE
  // ═══════════════════════════════════════════
  { id: "alz_early", name: "Alzheimer's Disease — Early Onset", icd10: "G30.0", dsm5: "331.0", category: "Dementia & Neurocognitive", description: "Alzheimer's disease with onset before age 65, typically presenting with prominent memory impairment but possibly atypical presentations (language, visuospatial, executive)." },
  { id: "alz_late", name: "Alzheimer's Disease — Late Onset", icd10: "G30.1", dsm5: "331.0", category: "Dementia & Neurocognitive", description: "Alzheimer's disease with onset at age 65 or later, the most common cause of dementia, characterised by progressive memory loss and multiple cognitive deficits." },
  { id: "alz_unspec", name: "Alzheimer's Disease — Unspecified", icd10: "G30.9", dsm5: "331.0", category: "Dementia & Neurocognitive", description: "Alzheimer's disease where age of onset is not specified; progressive neurodegenerative disorder with amyloid plaques and neurofibrillary tangles." },
  { id: "vascular_dem", name: "Vascular Dementia", icd10: "F01.50", dsm5: "290.40", category: "Dementia & Neurocognitive", description: "A major neurocognitive disorder caused by cerebrovascular disease, typically presenting with stepwise decline, executive dysfunction, and focal neurological signs." },
  { id: "ftd", name: "Frontotemporal Dementia", icd10: "G31.09", dsm5: "331.19", category: "Dementia & Neurocognitive", description: "A progressive neurodegenerative disorder affecting frontal and temporal lobes, presenting with behavioural disinhibition, apathy, language impairment (primary progressive aphasia), or executive dysfunction." },
  { id: "dlb", name: "Dementia with Lewy Bodies", icd10: "G31.83", dsm5: "331.82", category: "Dementia & Neurocognitive", description: "A progressive dementia characterised by fluctuating cognition, recurrent visual hallucinations, REM sleep behaviour disorder, and parkinsonism; sensitive to neuroleptics." },
  { id: "parkinsons_dem", name: "Parkinson's Disease Dementia", icd10: "F02.80", dsm5: "294.10", category: "Dementia & Neurocognitive", description: "Dementia developing in the context of established Parkinson's disease, typically with prominent executive dysfunction, visuospatial impairment, and psychiatric symptoms." },
  { id: "mixed_dem", name: "Mixed Dementia", icd10: "F03", dsm5: null, category: "Dementia & Neurocognitive", description: "Dementia with pathological features of more than one type (most commonly Alzheimer's disease plus vascular dementia), producing mixed clinical features." },
  { id: "mci", name: "Mild Cognitive Impairment", icd10: "G31.84", dsm5: "331.83", category: "Dementia & Neurocognitive", description: "Modest cognitive decline from a previous level of functioning that does not interfere with independence in everyday activities; often represents a prodromal phase of dementia." },
  { id: "korsakoff", name: "Korsakoff's Syndrome (Alcohol-Related Dementia)", icd10: "F10.96", dsm5: "291.1", category: "Dementia & Neurocognitive", description: "An amnestic syndrome caused by thiamine deficiency, usually in the context of chronic alcohol misuse, characterised by profound anterograde and retrograde amnesia with confabulation and relatively preserved intellect." },
  { id: "cjd", name: "Creutzfeldt-Jakob Disease", icd10: "A81.00", dsm5: null, category: "Dementia & Neurocognitive", description: "A rare, rapidly progressive prion disease causing dementia with myoclonus, ataxia, and distinctive EEG changes; uniformly fatal within months." },

  // ═══════════════════════════════════════════
  // MUSCULAR / PHYSICAL
  // ═══════════════════════════════════════════
  { id: "dmd", name: "Duchenne Muscular Dystrophy", icd10: "G71.01", dsm5: null, category: "Muscular/Physical", description: "A genetic, progressive muscle-wasting condition affecting primarily males, characterised by progressive proximal muscle weakness beginning in early childhood, loss of ambulation, and reduced life expectancy." },
  { id: "bmd", name: "Becker Muscular Dystrophy", icd10: "G71.01", dsm5: null, category: "Muscular/Physical", description: "A genetic, progressive muscle-wasting condition similar to Duchenne but with later onset and slower progression, characterised by progressive lower limb weakness, fatigue, and reduced endurance." },
  { id: "fshd", name: "Facioscapulohumeral Muscular Dystrophy", icd10: "G71.02", dsm5: null, category: "Muscular/Physical", description: "A genetic muscular dystrophy causing slowly progressive weakness of facial, scapular, and upper-arm muscles, with variable age of onset and rate of progression." },
  { id: "lgmd", name: "Limb-Girdle Muscular Dystrophy", icd10: "G71.09", dsm5: null, category: "Muscular/Physical", description: "A heterogeneous group of genetic muscular dystrophies characterised by progressive weakness of pelvic and shoulder girdle muscles, with variable inheritance patterns and age of onset." },
  { id: "myotonic_d1", name: "Myotonic Dystrophy Type 1", icd10: "G71.11", dsm5: null, category: "Muscular/Physical", description: "A genetic multisystem disorder with progressive muscle weakness, myotonia (delayed muscle relaxation), cataracts, cardiac conduction abnormalities, and cognitive involvement." },
  { id: "myotonic_d2", name: "Myotonic Dystrophy Type 2", icd10: "G71.11", dsm5: null, category: "Muscular/Physical", description: "A milder adult-onset variant of myotonic dystrophy with proximal weakness, myotonia, and multisystem involvement, typically without the congenital form seen in Type 1." },
  { id: "sma_1", name: "Spinal Muscular Atrophy Type I (Werdnig-Hoffmann)", icd10: "G12.0", dsm5: null, category: "Muscular/Physical", description: "The most severe infantile form of SMA, with onset before 6 months, inability to sit independently, and progressive weakness affecting breathing and swallowing." },
  { id: "sma_2", name: "Spinal Muscular Atrophy Type II", icd10: "G12.1", dsm5: null, category: "Muscular/Physical", description: "An intermediate form of SMA with onset between 6–18 months, inability to walk unaided but able to sit, with progressive respiratory and orthopaedic complications." },
  { id: "sma_3", name: "Spinal Muscular Atrophy Type III (Kugelberg-Welander)", icd10: "G12.1", dsm5: null, category: "Muscular/Physical", description: "A milder childhood-onset form of SMA with onset after 18 months, ability to walk at some point, but progressive proximal weakness and variable loss of ambulation." },
  { id: "sma_4", name: "Spinal Muscular Atrophy Type IV (Adult-Onset)", icd10: "G12.1", dsm5: null, category: "Muscular/Physical", description: "Adult-onset SMA (typically after age 30) with slowly progressive proximal weakness; ambulation usually preserved for many years." },
  { id: "cp_spastic_hemi", name: "Cerebral Palsy — Spastic Hemiplegia", icd10: "G80.2", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy with spasticity affecting one side of the body (arm and leg on the same side), typically due to unilateral perinatal brain injury." },
  { id: "cp_spastic_di", name: "Cerebral Palsy — Spastic Diplegia", icd10: "G80.1", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy with spasticity predominantly affecting the lower limbs, with relatively preserved upper-limb function; commonly associated with preterm birth and periventricular leukomalacia." },
  { id: "cp_spastic_quad", name: "Cerebral Palsy — Spastic Quadriplegia", icd10: "G80.0", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy with spasticity affecting all four limbs, typically the most severe form, often accompanied by intellectual disability, epilepsy, and dysphagia." },
  { id: "cp_dyskinetic", name: "Cerebral Palsy — Dyskinetic", icd10: "G80.3", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy characterised by involuntary, uncontrolled movements (dystonia, athetosis, or chorea) due to damage to the basal ganglia." },
  { id: "cp_ataxic", name: "Cerebral Palsy — Ataxic", icd10: "G80.4", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy characterised by problems with balance and coordination due to damage to the cerebellum." },
  { id: "cp_mixed", name: "Cerebral Palsy — Mixed", icd10: "G80.8", dsm5: null, category: "Muscular/Physical", description: "Cerebral palsy involving a combination of spastic, dyskinetic, and/or ataxic features." },
  { id: "sci_c", name: "Spinal Cord Injury — Cervical (Tetraplegia)", icd10: "G82.50", dsm5: null, category: "Muscular/Physical", description: "Injury to the cervical spinal cord resulting in impairment of motor and/or sensory function in all four limbs and trunk, with variable respiratory involvement depending on level." },
  { id: "sci_t", name: "Spinal Cord Injury — Thoracic (Paraplegia)", icd10: "G82.20", dsm5: null, category: "Muscular/Physical", description: "Injury to the thoracic spinal cord resulting in lower-limb impairment with preserved upper-limb function, and variable trunk control depending on level." },
  { id: "sci_l", name: "Spinal Cord Injury — Lumbar (Paraplegia)", icd10: "G82.22", dsm5: null, category: "Muscular/Physical", description: "Injury to the lumbar spinal cord resulting in impaired lower-limb function, bladder/bowel dysfunction, and variable hip and thigh strength depending on level." },
  { id: "spina_bifida", name: "Spina Bifida — Myelomeningocele", icd10: "Q05.9", dsm5: null, category: "Muscular/Physical", description: "A neural tube defect where the spinal column does not close completely during fetal development, resulting in variable degrees of paralysis, bladder/bowel dysfunction, and commonly associated hydrocephalus." },
  { id: "spina_bifida_occ", name: "Spina Bifida Occulta", icd10: "Q76.0", dsm5: null, category: "Muscular/Physical", description: "A mild form of spina bifida where a small gap exists in the spine but the spinal cord and meninges do not protrude; may be asymptomatic or cause tethered-cord symptoms." },
  { id: "hydrocephalus", name: "Hydrocephalus", icd10: "G91.9", dsm5: null, category: "Muscular/Physical", description: "Accumulation of cerebrospinal fluid within the ventricles of the brain, typically requiring shunt placement, with variable cognitive, motor, and visual consequences." },
  { id: "amp_upper", name: "Upper Limb Amputation (Acquired)", icd10: "Z89.2", dsm5: null, category: "Muscular/Physical", description: "Loss of an upper limb at any level, impacting activities of daily living, occupational performance, and body image; prosthetic rehabilitation may be indicated." },
  { id: "amp_lower", name: "Lower Limb Amputation (Acquired)", icd10: "Z89.5", dsm5: null, category: "Muscular/Physical", description: "Loss of a lower limb at any level (transtibial, transfemoral, hip disarticulation), impacting mobility, balance, and requiring prosthetic rehabilitation." },
  { id: "scoliosis_severe", name: "Severe Scoliosis", icd10: "M41.9", dsm5: null, category: "Muscular/Physical", description: "Significant lateral curvature of the spine (>40° Cobb angle), which may cause pain, reduced pulmonary function, and functional limitations in mobility and daily activities." },
  { id: "achondroplasia", name: "Achondroplasia (Skeletal Dysplasia)", icd10: "Q77.4", dsm5: null, category: "Muscular/Physical", description: "The most common form of short-limb dwarfism, caused by a FGFR3 mutation, with characteristic short stature, macrocephaly, midface hypoplasia, and potential orthopaedic and spinal complications." },
  { id: "oi", name: "Osteogenesis Imperfecta (Brittle Bone Disease)", icd10: "Q78.0", dsm5: null, category: "Muscular/Physical", description: "A genetic disorder affecting collagen production, characterised by fragile bones with increased fracture risk, variable short stature, blue sclerae, and dentinogenesis imperfecta." },
  { id: "arthrogryposis", name: "Arthrogryposis Multiplex Congenita", icd10: "Q74.3", dsm5: null, category: "Muscular/Physical", description: "A congenital condition characterised by multiple joint contractures present at birth, with variable muscle weakness; causes range from neurogenic to myopathic." },
  { id: "fibromyalgia", name: "Fibromyalgia", icd10: "M79.7", dsm5: null, category: "Muscular/Physical", description: "A chronic widespread pain condition characterised by musculoskeletal pain, fatigue, sleep disturbance, cognitive difficulties, and heightened sensitivity to sensory stimuli." },
  { id: "eds", name: "Ehlers-Danlos Syndrome", icd10: "Q79.6", dsm5: null, category: "Muscular/Physical", description: "A group of inherited connective tissue disorders characterised by joint hypermobility, skin hyperextensibility, tissue fragility, chronic pain, and fatigue." },
  { id: "hypermobility", name: "Joint Hypermobility Spectrum Disorder", icd10: "M35.7", dsm5: null, category: "Muscular/Physical", description: "A connective-tissue-related condition characterised by joint hypermobility with associated pain, fatigue, subluxations/dislocations, and autonomic symptoms; distinct from hypermobile EDS." },
  { id: "cfs", name: "Chronic Fatigue Syndrome / Myalgic Encephalomyelitis (ME/CFS)", icd10: "G93.32", dsm5: null, category: "Muscular/Physical", description: "A complex, chronic condition characterised by profound fatigue not improved by rest, post-exertional malaise, unrefreshing sleep, cognitive impairment, and orthostatic intolerance." },
  { id: "crps", name: "Complex Regional Pain Syndrome (CRPS)", icd10: "G90.50", dsm5: null, category: "Muscular/Physical", description: "A chronic pain condition usually affecting a limb following injury, characterised by severe pain disproportionate to the inciting event, sensory/motor/autonomic/trophic changes." },

  // ═══════════════════════════════════════════
  // GENETIC / CHROMOSOMAL
  // ═══════════════════════════════════════════
  { id: "down_syndrome", name: "Down Syndrome (Trisomy 21)", icd10: "Q90.9", dsm5: null, category: "Genetic", description: "A genetic condition caused by the presence of an extra copy of chromosome 21, resulting in intellectual disability, characteristic physical features, and increased risk of associated health conditions." },
  { id: "down_mosaic", name: "Down Syndrome — Mosaicism", icd10: "Q90.1", dsm5: null, category: "Genetic", description: "Down syndrome where only some cells carry the extra chromosome 21; clinical features may be milder than non-mosaic trisomy 21 but vary widely." },
  { id: "fragile_x", name: "Fragile X Syndrome", icd10: "Q99.2", dsm5: null, category: "Genetic", description: "A genetic condition caused by a mutation on the X chromosome, the most common inherited cause of intellectual disability, characterised by learning difficulties, behavioural challenges, and distinctive physical features." },
  { id: "fxtas", name: "Fragile X-Associated Tremor/Ataxia Syndrome", icd10: "G11.9", dsm5: null, category: "Genetic", description: "A late-onset neurodegenerative disorder in carriers of the FMR1 premutation, characterised by intention tremor, cerebellar ataxia, parkinsonism, and cognitive decline." },
  { id: "prader_willi", name: "Prader-Willi Syndrome", icd10: "Q87.1", dsm5: null, category: "Genetic", description: "A complex genetic condition characterised by hypotonia in infancy, hyperphagia (insatiable appetite), obesity, intellectual disability, behavioural challenges, and short stature." },
  { id: "angelman", name: "Angelman Syndrome", icd10: "Q93.51", dsm5: null, category: "Genetic", description: "A rare genetic condition affecting the nervous system, characterised by severe intellectual disability, speech impairment, movement and balance disorder, and a characteristically happy demeanour with frequent smiling and laughter." },
  { id: "williams", name: "Williams Syndrome", icd10: "Q93.82", dsm5: null, category: "Genetic", description: "A rare genetic condition characterised by cardiovascular disease, developmental delays, learning challenges, and a distinctive personality including overfriendliness and anxiety." },
  { id: "rett", name: "Rett Syndrome", icd10: "F84.2", dsm5: null, category: "Genetic", description: "A rare genetic neurological disorder affecting predominantly females, characterised by normal early development followed by loss of purposeful hand skills, slowed brain and head growth, seizures, and intellectual disability." },
  { id: "turner", name: "Turner Syndrome (45,X)", icd10: "Q96.9", dsm5: null, category: "Genetic", description: "A chromosomal condition in females caused by complete or partial absence of one X chromosome, characterised by short stature, ovarian insufficiency, lymphoedema, cardiac anomalies, and variable learning difficulties." },
  { id: "klinefelter", name: "Klinefelter Syndrome (47,XXY)", icd10: "Q98.4", dsm5: null, category: "Genetic", description: "A chromosomal condition in males with an additional X chromosome, characterised by tall stature, hypogonadism, infertility, and increased risk of learning difficulties and psychosocial challenges." },
  { id: "22q_del", name: "22q11.2 Deletion Syndrome (DiGeorge/Velocardiofacial)", icd10: "D82.1", dsm5: null, category: "Genetic", description: "A genetic condition caused by deletion of a small segment of chromosome 22, associated with cardiac anomalies, immune deficiency, palatal abnormalities, learning difficulties, and increased risk of psychotic disorders." },
  { id: "22q_dup", name: "22q11.2 Duplication Syndrome", icd10: "Q92.9", dsm5: null, category: "Genetic", description: "A highly variable genetic condition caused by duplication of a segment of chromosome 22, with developmental delay, learning difficulties, behavioural issues, and sometimes physical anomalies." },
  { id: "cri_du_chat", name: "Cri du Chat Syndrome (5p- Deletion)", icd10: "Q93.4", dsm5: null, category: "Genetic", description: "A rare chromosomal condition characterised by a high-pitched cat-like cry in infancy, intellectual disability, microcephaly, distinctive facial features, and developmental delay." },
  { id: "trisomy_18", name: "Trisomy 18 (Edwards Syndrome)", icd10: "Q91.3", dsm5: null, category: "Genetic", description: "A severe chromosomal condition caused by a third copy of chromosome 18, with major organ malformations, severe intellectual disability, and high perinatal mortality; survivors require intensive support." },
  { id: "trisomy_13", name: "Trisomy 13 (Patau Syndrome)", icd10: "Q91.7", dsm5: null, category: "Genetic", description: "A severe chromosomal condition caused by a third copy of chromosome 13, with major brain, cardiac, and facial malformations, severe intellectual disability, and high perinatal mortality." },
  { id: "smith_magenis", name: "Smith-Magenis Syndrome", icd10: "Q93.88", dsm5: null, category: "Genetic", description: "A rare chromosomal condition (17p11.2 deletion) characterised by intellectual disability, distinct behavioural phenotype including self-injury and attention-seeking, sleep disturbance, and craniofacial features." },
  { id: "phelan_mcdermid", name: "Phelan-McDermid Syndrome (22q13 Deletion)", icd10: "Q93.88", dsm5: null, category: "Genetic", description: "A rare chromosomal condition characterised by neonatal hypotonia, global developmental delay, severe speech impairment, autism features, and minor dysmorphic features." },
  { id: "kabuki", name: "Kabuki Syndrome", icd10: "Q87.89", dsm5: null, category: "Genetic", description: "A rare genetic disorder characterised by distinctive facial features resembling traditional Japanese Kabuki make-up, intellectual disability, skeletal anomalies, and recurrent infections." },
  { id: "charge", name: "CHARGE Syndrome", icd10: "Q87.8", dsm5: null, category: "Genetic", description: "A genetic disorder with a variable combination of Coloboma, Heart defects, Atresia choanae, Retardation of growth/development, Genital abnormalities, and Ear anomalies including deafness." },
  { id: "noonan", name: "Noonan Syndrome", icd10: "Q87.19", dsm5: null, category: "Genetic", description: "A genetic disorder characterised by distinctive facial features, short stature, congenital heart defects (especially pulmonary stenosis), developmental delay, and variable intellectual involvement." },
  { id: "cornelia_de_lange", name: "Cornelia de Lange Syndrome", icd10: "Q87.19", dsm5: null, category: "Genetic", description: "A rare genetic disorder with distinctive facial features, limb abnormalities, growth retardation, intellectual disability, and behavioural challenges including self-injury." },
  { id: "marfan", name: "Marfan Syndrome", icd10: "Q87.40", dsm5: null, category: "Genetic", description: "An autosomal dominant connective tissue disorder characterised by tall stature with long limbs, aortic root dilatation, lens dislocation, and skeletal manifestations." },
  { id: "pku", name: "Phenylketonuria (PKU)", icd10: "E70.0", dsm5: null, category: "Genetic", description: "An inherited metabolic disorder causing accumulation of phenylalanine; without dietary management from infancy, causes intellectual disability, seizures, and behavioural issues. With early management, outcomes are good." },
  { id: "mps", name: "Mucopolysaccharidosis", icd10: "E76.2", dsm5: null, category: "Genetic", description: "A group of inherited lysosomal storage disorders (types I–IX), with progressive accumulation of glycosaminoglycans causing multisystem involvement including skeletal dysplasia, cognitive decline, and organomegaly." },

  // ═══════════════════════════════════════════
  // SENSORY
  // ═══════════════════════════════════════════
  { id: "vision_mild", name: "Vision Impairment — Mild", icd10: "H54.6", dsm5: null, category: "Sensory", description: "Mild vision loss (visual acuity less than 6/12 but better than 6/18) impacting fine visual tasks, reading small print, and environmental scanning." },
  { id: "vision_moderate", name: "Vision Impairment — Moderate", icd10: "H54.7", dsm5: null, category: "Sensory", description: "Moderate vision loss (visual acuity 6/18 to less than 6/60) significantly impacting reading, mobility, and daily tasks, typically requiring low-vision aids." },
  { id: "vision_severe", name: "Vision Impairment — Severe", icd10: "H54.2", dsm5: null, category: "Sensory", description: "Severe vision loss (visual acuity 6/60 to 3/60) with major impact on functional vision; requires significant assistive technology and/or mobility training." },
  { id: "vision_blind", name: "Legal Blindness", icd10: "H54.0", dsm5: null, category: "Sensory", description: "Visual acuity less than 6/60 or visual field less than 10 degrees; significantly impacts all visually-guided activities; often requires braille, screen-reader technology, and orientation and mobility training." },
  { id: "cvi", name: "Cortical/Cerebral Visual Impairment (CVI)", icd10: "H47.619", dsm5: null, category: "Sensory", description: "Vision impairment due to damage to visual pathways or visual cortex of the brain rather than the eyes, common in children with neurological conditions; characterised by variable visual performance and visual processing deficits." },
  { id: "rp", name: "Retinitis Pigmentosa", icd10: "H35.52", dsm5: null, category: "Sensory", description: "A group of inherited retinal degenerations causing progressive loss of night vision followed by peripheral then central vision loss; tunnel vision is a hallmark." },
  { id: "amd", name: "Age-Related Macular Degeneration", icd10: "H35.30", dsm5: null, category: "Sensory", description: "A progressive retinal condition affecting central vision, impacting reading, driving, and face recognition; dry and wet subtypes with different prognoses and treatments." },
  { id: "congenital_cataract", name: "Congenital Cataract", icd10: "Q12.0", dsm5: null, category: "Sensory", description: "Opacity of the lens present at birth or developing in infancy, requiring early surgical intervention to prevent amblyopia and permanent visual deprivation." },
  { id: "glaucoma", name: "Glaucoma", icd10: "H40.9", dsm5: null, category: "Sensory", description: "A group of optic nerve disorders causing progressive visual field loss, typically associated with raised intraocular pressure; second leading cause of irreversible blindness globally." },
  { id: "hearing_mild", name: "Hearing Loss — Mild (26–40 dB)", icd10: "H90.3", dsm5: null, category: "Sensory", description: "Mild hearing loss affecting perception of soft speech and speech in background noise; hearing aids often beneficial." },
  { id: "hearing_moderate", name: "Hearing Loss — Moderate (41–70 dB)", icd10: "H90.3", dsm5: null, category: "Sensory", description: "Moderate hearing loss significantly impacting speech comprehension without amplification; requires hearing aids for daily communication." },
  { id: "hearing_severe", name: "Hearing Loss — Severe (71–90 dB)", icd10: "H90.3", dsm5: null, category: "Sensory", description: "Severe hearing loss with major impact on speech comprehension even with hearing aids; candidate for cochlear implantation or sign language communication." },
  { id: "hearing_profound", name: "Hearing Loss — Profound/Deafness (>90 dB)", icd10: "H90.5", dsm5: null, category: "Sensory", description: "Profound hearing loss or deafness; functional hearing for speech is absent even with amplification; candidates for cochlear implants and/or use Auslan as primary language." },
  { id: "deaf_blind", name: "Deafblindness (Combined Vision and Hearing Loss)", icd10: "H54 + H90", dsm5: null, category: "Sensory", description: "Combined vision and hearing loss that significantly affects communication, access to information, and mobility, requiring specialised support strategies." },
  { id: "usher", name: "Usher Syndrome", icd10: "H35.53", dsm5: null, category: "Sensory", description: "A genetic disorder causing congenital hearing loss plus progressive retinitis pigmentosa; a leading cause of deafblindness; types I–III vary in severity and onset." },
  { id: "apd", name: "Auditory Processing Disorder", icd10: "H93.25", dsm5: null, category: "Sensory", description: "A disorder of the central auditory system where the ears hear normally but the brain has difficulty interpreting sounds, particularly speech in background noise." },
  { id: "tinnitus", name: "Tinnitus (Severe/Chronic)", icd10: "H93.1", dsm5: null, category: "Sensory", description: "Persistent perception of sound (ringing, buzzing, hissing) without an external source; when severe, can significantly impact concentration, sleep, and emotional wellbeing." },

  // ═══════════════════════════════════════════
  // MEDICAL
  // ═══════════════════════════════════════════
  { id: "diabetes_t1", name: "Type 1 Diabetes Mellitus", icd10: "E10.9", dsm5: null, category: "Medical", description: "A chronic autoimmune condition in which the pancreas produces little or no insulin, requiring lifelong insulin management, blood glucose monitoring, and dietary management." },
  { id: "diabetes_t2", name: "Type 2 Diabetes Mellitus (with complications)", icd10: "E11.9", dsm5: null, category: "Medical", description: "A chronic metabolic condition characterised by insulin resistance and/or relative insulin deficiency, with functional impact commonly arising from complications such as neuropathy, retinopathy, nephropathy, or cardiovascular disease." },
  { id: "copd", name: "Chronic Obstructive Pulmonary Disease (COPD)", icd10: "J44.9", dsm5: null, category: "Medical", description: "A chronic inflammatory lung disease that causes obstructed airflow from the lungs, characterised by breathing difficulty, cough, mucus production, and reduced exercise tolerance." },
  { id: "asthma_severe", name: "Severe Asthma", icd10: "J45.50", dsm5: null, category: "Medical", description: "Chronic airway disease with frequent exacerbations despite high-dose treatment, significantly impacting exercise tolerance, school/work attendance, and requiring ongoing specialist management." },
  { id: "rheumatoid", name: "Rheumatoid Arthritis", icd10: "M06.9", dsm5: null, category: "Medical", description: "A chronic autoimmune inflammatory disorder affecting the joints, causing pain, swelling, stiffness, and progressive joint destruction leading to functional impairment." },
  { id: "lupus", name: "Systemic Lupus Erythematosus (SLE)", icd10: "M32.9", dsm5: null, category: "Medical", description: "A chronic multisystem autoimmune disease with variable manifestations including fatigue, rash, joint pain, and potentially serious renal, neurological, cardiac, or haematological involvement." },
  { id: "sjogren", name: "Sjögren's Syndrome", icd10: "M35.00", dsm5: null, category: "Medical", description: "A chronic autoimmune disease primarily affecting exocrine glands, causing dry eyes, dry mouth, fatigue, joint pain, and increased risk of lymphoma." },
  { id: "cystic_fibrosis", name: "Cystic Fibrosis", icd10: "E84.9", dsm5: null, category: "Medical", description: "An autosomal recessive genetic disorder affecting the lungs, pancreas, and other exocrine glands, causing progressive respiratory decline, malabsorption, and reduced life expectancy." },
  { id: "hiv", name: "HIV Disease", icd10: "B20", dsm5: null, category: "Medical", description: "Chronic viral infection causing progressive immune dysfunction; well-managed on antiretroviral therapy but may cause HIV-associated neurocognitive disorder and opportunistic complications." },
  { id: "ckd", name: "Chronic Kidney Disease (Stage 3–4)", icd10: "N18.9", dsm5: null, category: "Medical", description: "Progressive loss of kidney function with moderate-to-severe impairment (eGFR 15–59), causing fatigue, anaemia, bone-mineral issues, and cardiovascular risk." },
  { id: "esrd", name: "End-Stage Renal Disease (on Dialysis)", icd10: "N18.6", dsm5: null, category: "Medical", description: "Kidney failure (eGFR <15) requiring dialysis or transplantation, with significant impact on energy, dietary freedom, cognition, and daily routine." },
  { id: "liver_cirrhosis", name: "Liver Cirrhosis", icd10: "K74.60", dsm5: null, category: "Medical", description: "End-stage liver disease with irreversible scarring, causing portal hypertension, coagulopathy, hepatic encephalopathy, and progressive functional decline." },
  { id: "heart_failure", name: "Chronic Heart Failure", icd10: "I50.9", dsm5: null, category: "Medical", description: "A chronic condition where the heart cannot pump blood effectively, causing fatigue, dyspnoea, fluid retention, and reduced exercise tolerance." },
  { id: "cad", name: "Coronary Artery Disease", icd10: "I25.10", dsm5: null, category: "Medical", description: "Narrowing or blockage of coronary arteries causing angina, fatigue, and risk of myocardial infarction; functional impact from symptom burden and exercise limitation." },
  { id: "cancer_active", name: "Active Malignancy (Undergoing Treatment)", icd10: "C80.1", dsm5: null, category: "Medical", description: "Active cancer undergoing surgery, chemotherapy, radiotherapy, or immunotherapy; functional impact from disease burden plus treatment side effects including fatigue, neuropathy, and cognitive changes." },
  { id: "cancer_survivor", name: "Cancer Survivor — With Ongoing Sequelae", icd10: "Z85.9", dsm5: null, category: "Medical", description: "Person in remission or cured of cancer but with persistent functional consequences (e.g., chemo-induced neuropathy, cognitive changes, chronic pain, lymphoedema, fatigue)." },
  { id: "crohns", name: "Crohn's Disease", icd10: "K50.9", dsm5: null, category: "Medical", description: "A chronic inflammatory bowel disease that can affect any part of the gastrointestinal tract, causing pain, diarrhoea, malnutrition, fatigue, and extra-intestinal manifestations." },
  { id: "uc", name: "Ulcerative Colitis", icd10: "K51.9", dsm5: null, category: "Medical", description: "A chronic inflammatory bowel disease limited to the colon, causing bloody diarrhoea, urgency, abdominal pain, fatigue, and potential need for colectomy." },
  { id: "ibs", name: "Irritable Bowel Syndrome (Severe)", icd10: "K58.9", dsm5: null, category: "Medical", description: "A chronic functional gastrointestinal disorder with abdominal pain and altered bowel habit; in severe form can cause significant functional impairment and social anxiety." },
  { id: "chronic_pain", name: "Chronic Pain Syndrome", icd10: "G89.4", dsm5: null, category: "Medical", description: "Persistent pain beyond the expected healing period (typically >3 months) with associated functional, emotional, and social consequences; may be nociceptive, neuropathic, nociplastic, or mixed." },
  { id: "fnd", name: "Functional Neurological Disorder (FND)", icd10: "F44.4", dsm5: "300.11", category: "Medical", description: "A neurological disorder with genuine motor, sensory, or cognitive symptoms (e.g., non-epileptic seizures, functional weakness, tremor) that are inconsistent with or incompatible with recognised neurological disease." },
  { id: "somatic", name: "Somatic Symptom Disorder", icd10: "F45.1", dsm5: "300.82", category: "Medical", description: "A disorder characterised by one or more distressing somatic symptoms plus disproportionate thoughts, feelings, or behaviours related to those symptoms, causing significant impairment." },
  { id: "illness_anx", name: "Illness Anxiety Disorder (Hypochondriasis)", icd10: "F45.21", dsm5: "300.7", category: "Medical", description: "Preoccupation with having or acquiring a serious illness, with minimal somatic symptoms; high anxiety about health and disproportionate health-related behaviours." },
  { id: "medical_unspec", name: "Other Chronic Medical Condition (Complex/Rare)", icd10: "Z87.898", dsm5: null, category: "Medical", description: "Catch-all for complex or rare chronic medical conditions not otherwise classified that produce functional impairment relevant to NDIS supports." },

  // ─── Legacy IDs (preserved for backwards compatibility with saved reports) ───
  { id: "tbi", name: "Traumatic Brain Injury", icd10: "S06.9", dsm5: null, category: "Acquired Brain Injury", description: "Brain injury caused by an external mechanical force, resulting in temporary or permanent impairment of cognitive, physical, and psychosocial functions." },
  { id: "ms", name: "Multiple Sclerosis", icd10: "G35", dsm5: null, category: "Neurological", description: "A chronic, progressive autoimmune disease of the central nervous system causing demyelination, leading to variable symptoms including fatigue, mobility impairment, sensory disturbance, cognitive changes, and visual disturbance." },
  { id: "sci_para", name: "Spinal Cord Injury — Paraplegia", icd10: "G82.2", dsm5: null, category: "Muscular/Physical", description: "Injury to the spinal cord resulting in impairment or loss of motor and/or sensory function in the lower extremities, affecting mobility, bladder/bowel function, and sensation." },
  { id: "sci_tetra", name: "Spinal Cord Injury — Tetraplegia (Quadriplegia)", icd10: "G82.5", dsm5: null, category: "Muscular/Physical", description: "Injury to the spinal cord resulting in impairment or loss of motor and/or sensory function in all four limbs, trunk, and potentially respiratory function." },
  { id: "cp_spastic", name: "Cerebral Palsy — Spastic", icd10: "G80.0", dsm5: null, category: "Muscular/Physical", description: "A group of permanent movement disorders caused by non-progressive damage to the developing brain. Spastic type characterised by increased muscle tone, stiffness, and difficulty with voluntary movement." },
  { id: "22q", name: "22q11.2 Deletion Syndrome (DiGeorge/Velocardiofacial)", icd10: "D82.1", dsm5: null, category: "Genetic", description: "A genetic condition caused by deletion of a small segment of chromosome 22, associated with cardiac anomalies, immune deficiency, palatal abnormalities, learning difficulties, and increased risk of psychotic disorders." },
  { id: "deaf", name: "Sensorineural Hearing Loss — Bilateral", icd10: "H90.3", dsm5: null, category: "Sensory", description: "Permanent hearing loss in both ears caused by damage to the inner ear or auditory nerve, affecting communication, social interaction, and environmental awareness." },
  { id: "blind", name: "Visual Impairment — Legal Blindness", icd10: "H54.0", dsm5: null, category: "Sensory", description: "Visual acuity of 6/60 or less in the better eye with best correction, or a visual field of 10 degrees or less, significantly affecting mobility, daily living tasks, and independence." },
  { id: "deafblind", name: "Deafblindness (Dual Sensory Impairment)", icd10: "H54.0+H90.3", dsm5: null, category: "Sensory", description: "Combined hearing and vision loss that significantly affects communication, access to information, and mobility." },
  { id: "sad", name: "Schizoaffective Disorder (legacy alias)", icd10: "F25", dsm5: "295.70", category: "Psychosocial", description: "A disorder characterised by a combination of schizophrenia symptoms (hallucinations, delusions) and mood disorder symptoms (depression or mania)." },
];

export const DIAGNOSIS_CATEGORIES = [...new Set(DIAGNOSIS_LIBRARY.map(d => d.category))].sort();
